### ISSUE TITLE
Externally compiled modules must declare

### ISSUE THREAD

**Issue by EGVivo** [nakisen/asterisk-modules#1]
gcc -fPIC -shared res_pbxhelper.c
In file included from res_pbxhelper.c:1:0:
/usr/include/asterisk.h:234:2: error: #error "Externally compiled modules must declare AST_MODULE_SELF_SYM."
 #error "Externally compiled modules must declare AST_MODULE_SELF_SYM."

**Comment by nakisen** [comment]
I compile by copying the module to the asterisk source folder. If you are going to do this outside the source folder, you need to add the line "#define AST_MODULE_SELF_SYM __internal_my_module_self". Frankly, I don't have much experience since I haven't done "external compile" before.

``` c
//res_pbxhelper.c
#define AST_MODULE "res_pbxhelper"
#define AST_MODULE_SELF_SYM __internal_my_module_self

#include "asterisk.h"

#include <pjsip.h>
#include <pjsip_ua.h>
...
```

Or

Copy the module file under "<ast_source>/res/res_pbxhelper.c" and compile it using asterisk's compile system.

**Comment by EGVivo** [comment]
now i understand ,
i am trying to hook "core show channels" to hide some output using module do you have any idea how to do that??

**Comment by nakisen** [comment]
I don't know about this. You probably cannot change the result of any cli command by typing in module. However, you can register new cli commands. You can get detailed support from Asterisk developer forums.

https://community.asterisk.org/c/development/41

``` c
// add new cli funcs
static struct ast_cli_entry cli_myfunc_list[] = {
        AST_CLI_DEFINE(handle_cli_myfunc_show, "My New Func Show"),
        AST_CLI_DEFINE(handle_cli_myfunc_del, "My New Func Del"),
        AST_CLI_DEFINE(handle_cli_myfunc_set, "My New Func Set"),
};

static int unload_module(void)
{
...
    ast_cli_unregister_multiple(cli_myfunc_list, ARRAY_LEN(cli_myfunc_list));
...
}

static int load_module(void)
{
...
    ast_cli_register_multiple(cli_myfunc_list, ARRAY_LEN(cli_myfunc_list));
...
}
```
